// SPDX-License-Identifier: AGPL-3.0-or-later

//! Caddyfile generation from manifest-driven service topology.
//!
//! Generates reverse-proxy Caddyfile blocks deterministically from the
//! ecosystem manifest. Instead of hand-editing Caddyfiles with hardcoded
//! IPs, the manifest declares which gate hosts each service and this
//! module renders the corresponding Caddy vhost blocks.

use serde::{Deserialize, Serialize};
use std::fmt::{self, Write as _};

/// Default security headers applied to every TLS-enabled vhost.
///
/// Addresses EXP-01 (clickjacking, MIME sniffing, HSTS) from the
/// Wave 136 security sprint. Stripped `-Server` removes Caddy version
/// fingerprinting from responses.
const SECURITY_HEADER_BLOCK: &str = "\
    header {\n\
    \x20       Strict-Transport-Security \"max-age=63072000; includeSubDomains; preload\"\n\
    \x20       X-Content-Type-Options nosniff\n\
    \x20       X-Frame-Options DENY\n\
    \x20       X-XSS-Protection \"0\"\n\
    \x20       Referrer-Policy strict-origin-when-cross-origin\n\
    \x20       Permissions-Policy \"camera=(), microphone=(), geolocation=()\"\n\
    \x20       -Server\n\
    \x20   }";

/// A path-based sub-route within a Caddy vhost (renders as a `handle` block).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CaddySubRoute {
    /// Path matcher (e.g. `"/api/*"`, `"/ws"`). Empty = catch-all.
    pub path_prefix: String,
    /// Reverse proxy upstream for this sub-route.
    pub upstream: String,
}

/// A single Caddy vhost block — one domain/service mapping.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CaddyVhost {
    /// Domain name (e.g. `"primals.eco"`, `"git.primals.eco"`).
    pub domain: String,
    /// Reverse proxy upstream (e.g. `"10.13.37.1:3000"`).
    /// Used when `sub_routes` is empty; ignored when sub-routes are present.
    pub upstream: String,
    /// Optional path prefix for proxied routes (default: all paths).
    pub path: Option<String>,
    /// Whether to enable ACME TLS (default: true).
    pub tls: bool,
    /// Optional additional Caddy directives (header manipulation, etc.).
    pub extra_directives: Vec<String>,
    /// Path-based sub-routes within this domain (renders as `handle` blocks).
    /// When non-empty, the top-level `upstream`/`path` are ignored in favor
    /// of the sub-routes. More-specific paths must come first.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub sub_routes: Vec<CaddySubRoute>,
}

/// Full Caddyfile configuration for a gate.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CaddyConfig {
    /// Gate this config is generated for.
    pub gate_name: String,
    /// Global Caddy options (e.g. email for ACME).
    pub acme_email: Option<String>,
    /// Vhost blocks.
    pub vhosts: Vec<CaddyVhost>,
}

impl CaddyConfig {
    /// Render a Caddyfile from the config.
    #[must_use]
    pub fn to_caddyfile(&self) -> String {
        let mut out = String::with_capacity(1024);

        let _ = writeln!(
            out,
            "# Generated by cellMembrane for gate: {}",
            self.gate_name
        );
        let _ = writeln!(
            out,
            "# Do not edit manually — regenerate with: membrane caddy.generate"
        );
        let _ = writeln!(out);

        if let Some(email) = &self.acme_email {
            let _ = writeln!(out, "{{");
            let _ = writeln!(out, "    email {email}");
            let _ = writeln!(out, "}}");
            let _ = writeln!(out);
        }

        for vhost in &self.vhosts {
            let _ = writeln!(out, "{} {{", vhost.domain);

            if !vhost.sub_routes.is_empty() {
                for sub in &vhost.sub_routes {
                    if sub.path_prefix.is_empty() {
                        let _ = writeln!(out, "    handle {{");
                    } else {
                        let _ = writeln!(out, "    handle {} {{", sub.path_prefix);
                    }
                    let _ = writeln!(out, "        reverse_proxy {}", sub.upstream);
                    let _ = writeln!(out, "    }}");
                }
            } else if let Some(path) = &vhost.path {
                let _ = writeln!(out, "    reverse_proxy {path} {}", vhost.upstream);
            } else {
                let _ = writeln!(out, "    reverse_proxy {}", vhost.upstream);
            }

            if !vhost.tls {
                let _ = writeln!(out, "    tls off");
            }

            if vhost.tls {
                let _ = writeln!(out, "    {SECURITY_HEADER_BLOCK}");
            }

            for directive in &vhost.extra_directives {
                let _ = writeln!(out, "    {directive}");
            }

            let _ = writeln!(out, "}}");
            let _ = writeln!(out);
        }

        out
    }
}

impl fmt::Display for CaddyConfig {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.to_caddyfile())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_config() -> CaddyConfig {
        CaddyConfig {
            gate_name: "golgiBody-ext".into(),
            acme_email: Some("admin@primals.eco".into()),
            vhosts: vec![
                CaddyVhost {
                    domain: "primals.eco".into(),
                    upstream: "10.13.37.1:3000".into(),
                    path: None,
                    tls: true,
                    extra_directives: vec![],
                    sub_routes: vec![],
                },
                CaddyVhost {
                    domain: "git.primals.eco".into(),
                    upstream: "10.13.37.1:3000".into(),
                    path: None,
                    tls: true,
                    extra_directives: vec!["header X-Frame-Options DENY".into()],
                    sub_routes: vec![],
                },
                CaddyVhost {
                    domain: "depot.primals.eco".into(),
                    upstream: "10.13.37.1:8080".into(),
                    path: Some("/depot/*".into()),
                    tls: true,
                    extra_directives: vec![],
                    sub_routes: vec![],
                },
            ],
        }
    }

    #[test]
    fn caddyfile_renders_global_block() {
        let conf = sample_config();
        let output = conf.to_caddyfile();
        assert!(output.contains("email admin@primals.eco"));
    }

    #[test]
    fn caddyfile_renders_vhosts() {
        let conf = sample_config();
        let output = conf.to_caddyfile();
        assert!(output.contains("primals.eco {"));
        assert!(output.contains("reverse_proxy 10.13.37.1:3000"));
        assert!(output.contains("git.primals.eco {"));
    }

    #[test]
    fn caddyfile_path_proxy() {
        let conf = sample_config();
        let output = conf.to_caddyfile();
        assert!(output.contains("reverse_proxy /depot/* 10.13.37.1:8080"));
    }

    #[test]
    fn caddyfile_extra_directives() {
        let conf = sample_config();
        let output = conf.to_caddyfile();
        assert!(output.contains("header X-Frame-Options DENY"));
    }

    #[test]
    fn caddyfile_tls_off() {
        let conf = CaddyConfig {
            gate_name: "test".into(),
            acme_email: None,
            vhosts: vec![CaddyVhost {
                domain: "local.dev".into(),
                upstream: "127.0.0.1:8080".into(),
                path: None,
                tls: false,
                extra_directives: vec![],
                sub_routes: vec![],
            }],
        };
        let output = conf.to_caddyfile();
        assert!(output.contains("tls off"));
    }

    #[test]
    fn display_delegates_to_caddyfile() {
        let conf = sample_config();
        assert_eq!(conf.to_string(), conf.to_caddyfile());
    }

    #[test]
    fn serde_roundtrip() {
        let conf = sample_config();
        let json = serde_json::to_string(&conf).unwrap();
        let parsed: CaddyConfig = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.gate_name, "golgiBody-ext");
        assert_eq!(parsed.vhosts.len(), 3);
    }

    #[test]
    fn security_headers_on_tls_vhost() {
        let conf = sample_config();
        let output = conf.to_caddyfile();
        assert!(output.contains("Strict-Transport-Security"), "HSTS header");
        assert!(output.contains("X-Content-Type-Options nosniff"), "nosniff");
        assert!(output.contains("X-Frame-Options DENY"), "frame deny");
        assert!(output.contains("Referrer-Policy"), "referrer policy");
        assert!(output.contains("-Server"), "strip server header");
    }

    #[test]
    fn no_security_headers_on_tls_off() {
        let conf = CaddyConfig {
            gate_name: "test".into(),
            acme_email: None,
            vhosts: vec![CaddyVhost {
                domain: "local.dev".into(),
                upstream: "127.0.0.1:8080".into(),
                path: None,
                tls: false,
                extra_directives: vec![],
                sub_routes: vec![],
            }],
        };
        let output = conf.to_caddyfile();
        assert!(!output.contains("Strict-Transport-Security"), "no HSTS on plain HTTP");
    }

    #[test]
    fn no_acme_email_skips_global() {
        let conf = CaddyConfig {
            gate_name: "test".into(),
            acme_email: None,
            vhosts: vec![],
        };
        let output = conf.to_caddyfile();
        assert!(!output.contains("email"));
        assert!(!output.contains('{'));
    }

    #[test]
    fn sub_routes_render_handle_blocks() {
        let conf = CaddyConfig {
            gate_name: "test".into(),
            acme_email: None,
            vhosts: vec![CaddyVhost {
                domain: "footprint.primals.eco".into(),
                upstream: String::new(),
                path: None,
                tls: true,
                extra_directives: vec![],
                sub_routes: vec![
                    CaddySubRoute {
                        path_prefix: "/api/*".into(),
                        upstream: "10.13.37.1:8090".into(),
                    },
                    CaddySubRoute {
                        path_prefix: "/ws".into(),
                        upstream: "10.13.37.1:8080".into(),
                    },
                    CaddySubRoute {
                        path_prefix: String::new(),
                        upstream: "10.13.37.1:8080".into(),
                    },
                ],
            }],
        };
        let output = conf.to_caddyfile();
        assert!(output.contains("footprint.primals.eco {"), "domain block");
        assert!(output.contains("handle /api/* {"), "/api handle block");
        assert!(output.contains("reverse_proxy 10.13.37.1:8090"), "API upstream");
        assert!(output.contains("handle /ws {"), "/ws handle block");
        assert!(output.contains("handle {"), "catch-all handle block");
        assert!(output.contains("reverse_proxy 10.13.37.1:8080"), "petalTongue upstream");
        assert!(output.contains("Strict-Transport-Security"), "security headers");
    }

    #[test]
    fn sub_routes_skip_serialization_when_empty() {
        let vhost = CaddyVhost {
            domain: "test.primals.eco".into(),
            upstream: "127.0.0.1:8080".into(),
            path: None,
            tls: true,
            extra_directives: vec![],
            sub_routes: vec![],
        };
        let json = serde_json::to_string(&vhost).unwrap();
        assert!(!json.contains("sub_routes"), "empty sub_routes omitted from JSON");
    }

    #[test]
    fn sub_routes_serde_roundtrip() {
        let vhost = CaddyVhost {
            domain: "footprint.primals.eco".into(),
            upstream: String::new(),
            path: None,
            tls: true,
            extra_directives: vec![],
            sub_routes: vec![
                CaddySubRoute {
                    path_prefix: "/api/*".into(),
                    upstream: "10.13.37.1:8090".into(),
                },
                CaddySubRoute {
                    path_prefix: String::new(),
                    upstream: "10.13.37.1:8080".into(),
                },
            ],
        };
        let json = serde_json::to_string(&vhost).unwrap();
        let parsed: CaddyVhost = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.sub_routes.len(), 2);
        assert_eq!(parsed.sub_routes[0].path_prefix, "/api/*");
    }
}
