// SPDX-License-Identifier: AGPL-3.0-or-later

//! Sovereign DNS zone configuration — knot-dns zone file and config generation.
//!
//! Generates zone files and `knot.conf` fragments deterministically from the
//! ecosystem manifest. Instead of hand-editing zone files, the manifest declares
//! gate IPs and domain roles, and this module renders the corresponding DNS
//! records and knot-dns configuration.
//!
//! Mirrors the pattern established by [`crate::caddy`] for Caddyfile generation.

use serde::{Deserialize, Serialize};
use std::fmt::{self, Write as _};

/// A single DNS resource record.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct DnsRecord {
    /// Record name (e.g. `"@"`, `"git"`, `"depot"`, `"sporegate"`).
    pub name: String,
    /// TTL in seconds (0 = use zone default).
    pub ttl: u32,
    /// Record type (e.g. `"A"`, `"AAAA"`, `"CNAME"`, `"NS"`, `"MX"`, `"TXT"`).
    pub rtype: String,
    /// Record data (e.g. `"10.13.37.1"`, `"ns1.primals.eco."`).
    pub rdata: String,
}

/// A DNS zone containing all records for a single domain.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DnsZone {
    /// Zone origin (e.g. `"primals.eco"`, `"primals.local"`).
    pub origin: String,
    /// SOA primary nameserver (e.g. `"ns1.primals.eco."`).
    pub soa_mname: String,
    /// SOA responsible party email in DNS format (e.g. `"admin.primals.eco."`).
    pub soa_rname: String,
    /// SOA serial (YYYYMMDDNN format recommended).
    pub soa_serial: u32,
    /// SOA refresh interval in seconds.
    pub soa_refresh: u32,
    /// SOA retry interval in seconds.
    pub soa_retry: u32,
    /// SOA expire time in seconds.
    pub soa_expire: u32,
    /// SOA negative cache TTL.
    pub soa_minimum: u32,
    /// Default TTL for records in this zone.
    pub default_ttl: u32,
    /// Resource records.
    pub records: Vec<DnsRecord>,
}

impl Default for DnsZone {
    fn default() -> Self {
        Self {
            origin: String::new(),
            soa_mname: String::new(),
            soa_rname: String::new(),
            soa_serial: 1,
            soa_refresh: 3600,
            soa_retry: 900,
            soa_expire: 604_800,
            soa_minimum: 86_400,
            default_ttl: 3600,
            records: Vec::new(),
        }
    }
}

impl DnsZone {
    /// Render the zone as a standard BIND/knot-compatible zone file.
    #[must_use]
    pub fn to_zonefile(&self) -> String {
        let mut out = String::with_capacity(1024);

        let _ = writeln!(
            out,
            "; Zone file for {} — generated by cellMembrane",
            self.origin
        );
        let _ = writeln!(out, "$ORIGIN {}.", self.origin);
        let _ = writeln!(out, "$TTL {}", self.default_ttl);
        let _ = writeln!(out);

        let _ = writeln!(
            out,
            "{pad}IN  SOA  {mname} {rname} (",
            pad = "@".to_string() + &" ".repeat(7),
            mname = self.soa_mname,
            rname = self.soa_rname,
        );
        let _ = writeln!(out, "        {:<12} ; serial", self.soa_serial);
        let _ = writeln!(out, "        {:<12} ; refresh", self.soa_refresh);
        let _ = writeln!(out, "        {:<12} ; retry", self.soa_retry);
        let _ = writeln!(out, "        {:<12} ; expire", self.soa_expire);
        let _ = writeln!(out, "        {:<12} ; minimum", self.soa_minimum);
        let _ = writeln!(out, "        )");
        let _ = writeln!(out);

        for rec in &self.records {
            if rec.ttl > 0 && rec.ttl != self.default_ttl {
                let _ = writeln!(
                    out,
                    "{:<16} {} IN  {:<6} {}",
                    rec.name, rec.ttl, rec.rtype, rec.rdata
                );
            } else {
                let _ = writeln!(
                    out,
                    "{:<16} IN  {:<6} {}",
                    rec.name, rec.rtype, rec.rdata
                );
            }
        }

        out
    }
}

/// Full knot-dns configuration for a gate.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct KnotConfig {
    /// Gate this config is generated for.
    pub gate_name: String,
    /// Zones to serve.
    pub zones: Vec<DnsZone>,
    /// Whether DNSSEC signing is enabled.
    pub dnssec: bool,
    /// Listen addresses (e.g. `["0.0.0.0@53"]`).
    pub listen: Vec<String>,
}

impl KnotConfig {
    /// Render a `knot.conf` configuration fragment.
    ///
    /// Generates the `server`, `zone`, and optionally `policy`/`template`
    /// sections for knot-dns. Does not include `remote`/`acl` sections
    /// (those are gate-specific and managed separately).
    #[must_use]
    pub fn to_knot_conf(&self) -> String {
        use crate::service::{DEFAULT_KNOT_ZONE_DIR};

        let mut out = String::with_capacity(1024);

        let _ = writeln!(
            out,
            "# knot.conf — generated by cellMembrane for gate: {}",
            self.gate_name
        );
        let _ = writeln!(out);

        let _ = writeln!(out, "server:");
        for addr in &self.listen {
            let _ = writeln!(out, "  listen: {addr}");
        }
        let _ = writeln!(out, "  rundir: /run/knot");
        let _ = writeln!(out, "  user: knot:knot");
        let _ = writeln!(out);

        let _ = writeln!(out, "log:");
        let _ = writeln!(out, "  - target: syslog");
        let _ = writeln!(out, "    any: info");
        let _ = writeln!(out);

        if self.dnssec {
            let _ = writeln!(out, "policy:");
            let _ = writeln!(out, "  - id: membrane-dnssec");
            let _ = writeln!(out, "    algorithm: ecdsap256sha256");
            let _ = writeln!(out, "    ksk-lifetime: 365d");
            let _ = writeln!(out, "    zsk-lifetime: 90d");
            let _ = writeln!(out, "    nsec3: on");
            let _ = writeln!(out);

            let _ = writeln!(out, "template:");
            let _ = writeln!(out, "  - id: membrane-signed");
            let _ = writeln!(out, "    dnssec-signing: on");
            let _ = writeln!(out, "    dnssec-policy: membrane-dnssec");
            let _ = writeln!(out, "    storage: {DEFAULT_KNOT_ZONE_DIR}");
            let _ = writeln!(out, "    file: \"%s.zone\"");
            let _ = writeln!(out);
        }

        let _ = writeln!(out, "zone:");
        for zone in &self.zones {
            let _ = writeln!(out, "  - domain: {}", zone.origin);
            let _ = writeln!(out, "    storage: {DEFAULT_KNOT_ZONE_DIR}");
            let _ = writeln!(out, "    file: \"{}.zone\"", zone.origin);
            if self.dnssec {
                let _ = writeln!(out, "    template: membrane-signed");
            }
        }

        out
    }
}

impl fmt::Display for DnsRecord {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        if self.ttl > 0 {
            write!(f, "{} {} IN {} {}", self.name, self.ttl, self.rtype, self.rdata)
        } else {
            write!(f, "{} IN {} {}", self.name, self.rtype, self.rdata)
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_zone() -> DnsZone {
        DnsZone {
            origin: "primals.eco".into(),
            soa_mname: "ns1.primals.eco.".into(),
            soa_rname: "admin.primals.eco.".into(),
            soa_serial: 2_026_072_901,
            default_ttl: 3600,
            records: vec![
                DnsRecord {
                    name: "@".into(),
                    ttl: 0,
                    rtype: "NS".into(),
                    rdata: "ns1.primals.eco.".into(),
                },
                DnsRecord {
                    name: "ns1".into(),
                    ttl: 0,
                    rtype: "A".into(),
                    rdata: "10.13.37.1".into(),
                },
                DnsRecord {
                    name: "git".into(),
                    ttl: 0,
                    rtype: "A".into(),
                    rdata: "10.13.37.1".into(),
                },
                DnsRecord {
                    name: "depot".into(),
                    ttl: 0,
                    rtype: "A".into(),
                    rdata: "10.13.37.1".into(),
                },
            ],
            ..Default::default()
        }
    }

    #[test]
    fn zonefile_has_soa() {
        let zone = sample_zone();
        let zf = zone.to_zonefile();
        assert!(zf.contains("SOA"), "zone file must have SOA record");
        assert!(zf.contains("ns1.primals.eco."), "SOA must contain mname");
        assert!(zf.contains("2026072901"), "SOA must contain serial");
    }

    #[test]
    fn zonefile_has_origin() {
        let zone = sample_zone();
        let zf = zone.to_zonefile();
        assert!(zf.contains("$ORIGIN primals.eco."));
    }

    #[test]
    fn zonefile_has_records() {
        let zone = sample_zone();
        let zf = zone.to_zonefile();
        assert!(zf.contains("NS"));
        assert!(zf.contains("git"));
        assert!(zf.contains("depot"));
        assert!(zf.contains("10.13.37.1"));
    }

    #[test]
    fn zonefile_ttl_override() {
        let zone = DnsZone {
            origin: "test.local".into(),
            soa_mname: "ns.test.local.".into(),
            soa_rname: "admin.test.local.".into(),
            soa_serial: 1,
            default_ttl: 3600,
            records: vec![DnsRecord {
                name: "fast".into(),
                ttl: 60,
                rtype: "A".into(),
                rdata: "1.2.3.4".into(),
            }],
            ..Default::default()
        };
        let zf = zone.to_zonefile();
        assert!(
            zf.contains("60"),
            "record with non-default TTL should show TTL"
        );
    }

    #[test]
    fn knot_conf_has_server_section() {
        let config = KnotConfig {
            gate_name: "golgiBody".into(),
            zones: vec![sample_zone()],
            dnssec: false,
            listen: vec!["0.0.0.0@53".into(), "::@53".into()],
        };
        let conf = config.to_knot_conf();
        assert!(conf.contains("server:"));
        assert!(conf.contains("listen: 0.0.0.0@53"));
        assert!(conf.contains("listen: ::@53"));
    }

    #[test]
    fn knot_conf_has_zone_section() {
        let config = KnotConfig {
            gate_name: "golgiBody".into(),
            zones: vec![sample_zone()],
            dnssec: false,
            listen: vec!["0.0.0.0@53".into()],
        };
        let conf = config.to_knot_conf();
        assert!(conf.contains("zone:"));
        assert!(conf.contains("domain: primals.eco"));
    }

    #[test]
    fn knot_conf_dnssec_policy() {
        let config = KnotConfig {
            gate_name: "golgiBody".into(),
            zones: vec![sample_zone()],
            dnssec: true,
            listen: vec!["0.0.0.0@53".into()],
        };
        let conf = config.to_knot_conf();
        assert!(conf.contains("policy:"));
        assert!(conf.contains("membrane-dnssec"));
        assert!(conf.contains("ecdsap256sha256"));
        assert!(conf.contains("template: membrane-signed"));
    }

    #[test]
    fn knot_conf_no_dnssec_when_disabled() {
        let config = KnotConfig {
            gate_name: "test".into(),
            zones: vec![sample_zone()],
            dnssec: false,
            listen: vec!["0.0.0.0@53".into()],
        };
        let conf = config.to_knot_conf();
        assert!(!conf.contains("policy:"));
        assert!(!conf.contains("dnssec-signing"));
    }

    #[test]
    fn dns_record_display() {
        let rec = DnsRecord {
            name: "git".into(),
            ttl: 3600,
            rtype: "A".into(),
            rdata: "10.13.37.1".into(),
        };
        let s = rec.to_string();
        assert!(s.contains("git"));
        assert!(s.contains('A'));
        assert!(s.contains("10.13.37.1"));
    }

    #[test]
    fn dns_zone_default_has_sane_timers() {
        let zone = DnsZone::default();
        assert_eq!(zone.soa_refresh, 3600);
        assert_eq!(zone.soa_retry, 900);
        assert!(zone.soa_expire > zone.soa_refresh);
    }
}
