// SPDX-License-Identifier: AGPL-3.0-or-later

//! Sovereign defense layer — wiring between external host-level services
//! (fail2ban, nftables, systemd) and the inner membrane (primals, mesh topology).
//!
//! # Problem
//!
//! External sovereign defenses (fail2ban) operate blindly relative to the mesh.
//! During high-frequency cascade pushes, mesh gate IPs can be banned by fail2ban
//! because repeated SSH/git connections look like brute-force attacks. The
//! membrane must derive correct whitelists from its own topology and push them
//! to sovereign defense tools.
//!
//! # Design
//!
//! The sovereign defense layer sits at the boundary between K-Derm layers:
//!
//! ```text
//! ┌─────────────────────────────────────────────────┐
//! │  Extracellular (internet scanners, attackers)    │
//! ├─────────────────────────────────────────────────┤
//! │  Outer Membrane (fail2ban, nftables)             │  ← sovereign defense
//! ├─────────────────────────────────────────────────┤
//! │  Periplasm (golgiBody relay services)            │
//! ├─────────────────────────────────────────────────┤
//! │  Plasma Membrane (WireGuard, Tower Atomic)       │  ← mesh topology
//! ├─────────────────────────────────────────────────┤
//! │  Cytoplasm (primals, UDS IPC)                    │
//! └─────────────────────────────────────────────────┘
//! ```
//!
//! The key insight: fail2ban must whitelist everything at and below the plasma
//! membrane (WireGuard IPs, NAT WAN IPs for LAN gates, localhost). Anything
//! outside the outer membrane is untrusted and should remain subject to
//! fail2ban's rate limiting.

use serde::{Deserialize, Serialize};
use std::fmt;

/// A fail2ban jail configuration derived from membrane topology.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Fail2banJail {
    /// Jail name (e.g. `"sshd"`, `"forgejo-ssh"`).
    pub name: String,
    /// Port number the jail protects.
    pub port: u16,
    /// Filter name (fail2ban filter definition).
    pub filter: String,
    /// Maximum retries before ban.
    pub maxretry: u32,
    /// Ban duration in seconds.
    pub bantime: u32,
    /// Window for counting failures in seconds.
    pub findtime: u32,
    /// Systemd backend.
    pub backend: Fail2banBackend,
}

/// Fail2ban log backend.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Fail2banBackend {
    /// Read from systemd journal.
    Systemd,
    /// Read from log file.
    Auto,
}

impl fmt::Display for Fail2banBackend {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Systemd => write!(f, "systemd"),
            Self::Auto => write!(f, "auto"),
        }
    }
}

/// Sovereign defense configuration for a membrane host.
///
/// Generated from mesh topology — the membrane derives fail2ban whitelists
/// from its own gate registry rather than requiring manual IP management.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SovereignDefenseConfig {
    /// IPs/CIDRs that must never be banned (mesh-internal traffic).
    pub ignore_ips: Vec<String>,
    /// Jail definitions (one per protected port).
    pub jails: Vec<Fail2banJail>,
}

impl SovereignDefenseConfig {
    /// Derive the default `ignoreip` list from mesh topology.
    ///
    /// Includes:
    /// - `127.0.0.1/8` and `::1` (localhost)
    /// - The entire WireGuard subnet (`10.13.37.0/24`)
    /// - All known WAN NAT IPs for gates behind NAT
    #[must_use]
    pub fn derive_ignore_ips(wg_subnet: &str, wan_nat_ips: &[&str]) -> Vec<String> {
        let mut ips = vec![
            "127.0.0.1/8".to_string(),
            "::1".to_string(),
            wg_subnet.to_string(),
        ];
        for ip in wan_nat_ips {
            if !ips.iter().any(|existing| existing == *ip) {
                ips.push((*ip).to_string());
            }
        }
        ips
    }

    /// Generate a fail2ban `jail.local` configuration file.
    #[must_use]
    pub fn to_jail_local(&self) -> String {
        let mut out = String::with_capacity(1024);
        out.push_str(
            "# Sovereign defense — generated by cellMembrane\n\
             # Whitelists inner-membrane gate IPs so mesh operations\n\
             # are never blocked by fail2ban during high-frequency pushes.\n\n",
        );

        out.push_str("[DEFAULT]\n");
        out.push_str("ignoreip = ");
        out.push_str(&self.ignore_ips.join(" "));
        out.push_str("\n\n");

        for jail in &self.jails {
            out.push_str(&format!("[{}]\n", jail.name));
            out.push_str("enabled = true\n");
            if jail.port != 22 {
                out.push_str(&format!("port = {}\n", jail.port));
            }
            out.push_str(&format!("filter = {}\n", jail.filter));
            out.push_str(&format!("backend = {}\n", jail.backend));
            out.push_str(&format!("maxretry = {}\n", jail.maxretry));
            out.push_str(&format!("bantime = {}\n", jail.bantime));
            out.push_str(&format!("findtime = {}\n", jail.findtime));
            out.push('\n');
        }

        out
    }

    /// Default sovereign defense config for golgiBody (sole VPS).
    ///
    /// Protects SSH (port 22) and Forgejo SSH (port 2222) while whitelisting
    /// all mesh gate traffic.
    #[must_use]
    pub fn golgi_default(wg_subnet: &str, wan_nat_ips: &[&str]) -> Self {
        let ignore_ips = Self::derive_ignore_ips(wg_subnet, wan_nat_ips);
        Self {
            ignore_ips,
            jails: vec![
                Fail2banJail {
                    name: "sshd".to_string(),
                    port: 22,
                    filter: "sshd".to_string(),
                    maxretry: 5,
                    bantime: 3600,
                    findtime: 600,
                    backend: Fail2banBackend::Systemd,
                },
                Fail2banJail {
                    name: "forgejo-ssh".to_string(),
                    port: 2222,
                    filter: "sshd".to_string(),
                    maxretry: 5,
                    bantime: 3600,
                    findtime: 600,
                    backend: Fail2banBackend::Systemd,
                },
            ],
        }
    }
}

/// Result of probing a fail2ban jail's status.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JailStatus {
    /// Jail name.
    pub name: String,
    /// Number of currently banned IPs.
    pub currently_banned: u32,
    /// Total bans since last restart.
    pub total_banned: u32,
    /// Currently failed attempts.
    pub currently_failed: u32,
    /// Total failed attempts since last restart.
    pub total_failed: u32,
    /// List of currently banned IPs.
    pub banned_ips: Vec<String>,
    /// Whether any mesh gate IP is currently banned (critical alert).
    pub mesh_gate_banned: bool,
}

/// Aggregated sovereign defense health for a host.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SovereignDefenseHealth {
    /// Whether fail2ban is running.
    pub fail2ban_active: bool,
    /// Whether the mesh whitelist is correctly configured.
    pub whitelist_valid: bool,
    /// Per-jail status.
    pub jails: Vec<JailStatus>,
    /// Whether any mesh gate IP is currently banned across any jail.
    pub mesh_gate_blocked: bool,
}

impl SovereignDefenseHealth {
    /// Quick severity assessment.
    #[must_use]
    pub fn severity(&self) -> SovereignSeverity {
        if self.mesh_gate_blocked {
            return SovereignSeverity::Critical;
        }
        if !self.fail2ban_active || !self.whitelist_valid {
            return SovereignSeverity::Warning;
        }
        SovereignSeverity::Healthy
    }
}

/// Severity level for sovereign defense health.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum SovereignSeverity {
    /// All good — fail2ban running, whitelist correct, no mesh gates banned.
    Healthy,
    /// Degraded — fail2ban down or whitelist misconfigured, but no mesh gates blocked.
    Warning,
    /// Mesh gate traffic is being blocked — immediate action required.
    Critical,
}

impl fmt::Display for SovereignSeverity {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Healthy => write!(f, "HEALTHY"),
            Self::Warning => write!(f, "WARNING"),
            Self::Critical => write!(f, "CRITICAL"),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn derive_ignore_ips_includes_all_sources() {
        let ips = SovereignDefenseConfig::derive_ignore_ips(
            "10.13.37.0/24",
            &["162.226.225.148", "24.128.136.74"],
        );
        assert!(ips.contains(&"127.0.0.1/8".to_string()));
        assert!(ips.contains(&"::1".to_string()));
        assert!(ips.contains(&"10.13.37.0/24".to_string()));
        assert!(ips.contains(&"162.226.225.148".to_string()));
        assert!(ips.contains(&"24.128.136.74".to_string()));
    }

    #[test]
    fn derive_ignore_ips_deduplicates() {
        let ips = SovereignDefenseConfig::derive_ignore_ips(
            "10.13.37.0/24",
            &["10.13.37.0/24", "1.2.3.4"],
        );
        assert_eq!(
            ips.iter().filter(|ip| *ip == "10.13.37.0/24").count(),
            1,
            "WG subnet should not be duplicated"
        );
    }

    #[test]
    fn golgi_default_has_two_jails() {
        let cfg = SovereignDefenseConfig::golgi_default("10.13.37.0/24", &["162.226.225.148"]);
        assert_eq!(cfg.jails.len(), 2);
        assert_eq!(cfg.jails[0].name, "sshd");
        assert_eq!(cfg.jails[1].name, "forgejo-ssh");
        assert_eq!(cfg.jails[1].port, 2222);
    }

    #[test]
    fn jail_local_contains_ignoreip() {
        let cfg = SovereignDefenseConfig::golgi_default(
            "10.13.37.0/24",
            &["162.226.225.148", "24.128.136.74"],
        );
        let output = cfg.to_jail_local();
        assert!(output.contains("ignoreip = "));
        assert!(output.contains("10.13.37.0/24"));
        assert!(output.contains("162.226.225.148"));
        assert!(output.contains("24.128.136.74"));
        assert!(output.contains("[sshd]"));
        assert!(output.contains("[forgejo-ssh]"));
        assert!(output.contains("maxretry = 5"));
    }

    #[test]
    fn severity_critical_when_mesh_blocked() {
        let health = SovereignDefenseHealth {
            fail2ban_active: true,
            whitelist_valid: true,
            jails: vec![],
            mesh_gate_blocked: true,
        };
        assert_eq!(health.severity(), SovereignSeverity::Critical);
    }

    #[test]
    fn severity_warning_when_fail2ban_down() {
        let health = SovereignDefenseHealth {
            fail2ban_active: false,
            whitelist_valid: true,
            jails: vec![],
            mesh_gate_blocked: false,
        };
        assert_eq!(health.severity(), SovereignSeverity::Warning);
    }

    #[test]
    fn severity_healthy_when_all_good() {
        let health = SovereignDefenseHealth {
            fail2ban_active: true,
            whitelist_valid: true,
            jails: vec![],
            mesh_gate_blocked: false,
        };
        assert_eq!(health.severity(), SovereignSeverity::Healthy);
    }
}
