// SPDX-License-Identifier: AGPL-3.0-or-later

//! `WireGuard` configuration generation from manifest-driven peer topology.
//!
//! Generates `wg-quick`-compatible config files deterministically from the
//! ecosystem manifest gate profiles. Each gate's `wg_ip` defines its mesh
//! address, and all other gates become peers. Private keys are NOT stored
//! in the manifest — the generator emits a placeholder that the operator
//! fills in (or reads from a local keyfile).

use serde::{Deserialize, Serialize};
use std::fmt::{self, Write as _};

/// Default `WireGuard` listen port.
pub const DEFAULT_WG_PORT: u16 = 51820;

/// Default `WireGuard` interface name.
pub const DEFAULT_WG_IFACE: &str = "wg0";

/// A peer entry in the mesh.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct WgPeer {
    /// Gate identity name (e.g. `"golgi"`).
    pub name: String,
    /// Mesh IP address (e.g. `"10.13.37.1"`).
    pub mesh_ip: String,
    /// Optional public key (from local keystore or manifest extension).
    pub public_key: Option<String>,
    /// Optional endpoint for peers that have a known public address.
    pub endpoint: Option<String>,
    /// `AllowedIPs` for this peer (default: `{mesh_ip}/32`).
    pub allowed_ips: Vec<String>,
    /// Persistent keepalive interval (seconds). `0` = disabled.
    pub keepalive: u16,
}

/// `WireGuard` config for a single gate.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WgConfig {
    /// Gate this config is generated for.
    pub gate_name: String,
    /// This gate's mesh IP.
    pub address: String,
    /// Listen port.
    pub listen_port: u16,
    /// Mesh subnet CIDR.
    pub subnet: String,
    /// Peers in the mesh (all other gates).
    pub peers: Vec<WgPeer>,
}

impl WgConfig {
    /// Render a `wg-quick`-compatible config file.
    ///
    /// Private key is emitted as a placeholder — the operator must fill it in
    /// or point to a keyfile via `PostUp`.
    #[must_use]
    pub fn to_wg_quick(&self) -> String {
        let mut out = String::with_capacity(512);

        let _ = writeln!(
            out,
            "# Generated by cellMembrane for gate: {}",
            self.gate_name
        );
        let _ = writeln!(out, "# Mesh subnet: {}", self.subnet);
        let _ = writeln!(out);
        let _ = writeln!(out, "[Interface]");
        let _ = writeln!(out, "Address = {}/24", self.address);
        let _ = writeln!(out, "ListenPort = {}", self.listen_port);
        let _ = writeln!(out, "PrivateKey = <PRIVATE_KEY>");
        let _ = writeln!(out);

        for peer in &self.peers {
            let _ = writeln!(out, "# {}", peer.name);
            let _ = writeln!(out, "[Peer]");
            let pubkey = peer.public_key.as_deref().unwrap_or("<PUBLIC_KEY>");
            let _ = writeln!(out, "PublicKey = {pubkey}");

            let allowed = if peer.allowed_ips.is_empty() {
                format!("{}/32", peer.mesh_ip)
            } else {
                peer.allowed_ips.join(", ")
            };
            let _ = writeln!(out, "AllowedIPs = {allowed}");

            if let Some(endpoint) = &peer.endpoint {
                let _ = writeln!(out, "Endpoint = {endpoint}:{}", self.listen_port);
            }
            if peer.keepalive > 0 {
                let _ = writeln!(out, "PersistentKeepalive = {}", peer.keepalive);
            }
            let _ = writeln!(out);
        }

        out
    }
}

impl fmt::Display for WgConfig {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.to_wg_quick())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_config() -> WgConfig {
        WgConfig {
            gate_name: "sporeGate".into(),
            address: "10.13.37.2".into(),
            listen_port: DEFAULT_WG_PORT,
            subnet: "10.13.37.0/24".into(),
            peers: vec![
                WgPeer {
                    name: "golgi".into(),
                    mesh_ip: "10.13.37.1".into(),
                    public_key: Some("abc123==".into()),
                    endpoint: Some("157.230.3.183".into()),
                    allowed_ips: vec!["10.13.37.1/32".into()],
                    keepalive: 25,
                },
                WgPeer {
                    name: "eastGate".into(),
                    mesh_ip: "10.13.37.5".into(),
                    public_key: None,
                    endpoint: None,
                    allowed_ips: vec![],
                    keepalive: 0,
                },
            ],
        }
    }

    #[test]
    fn wg_quick_format_renders() {
        let conf = sample_config();
        let output = conf.to_wg_quick();
        assert!(output.contains("[Interface]"));
        assert!(output.contains("Address = 10.13.37.2/24"));
        assert!(output.contains("ListenPort = 51820"));
        assert!(output.contains("PrivateKey = <PRIVATE_KEY>"));
    }

    #[test]
    fn wg_quick_peers_rendered() {
        let conf = sample_config();
        let output = conf.to_wg_quick();
        assert!(output.contains("# golgi"));
        assert!(output.contains("PublicKey = abc123=="));
        assert!(output.contains("Endpoint = 157.230.3.183:51820"));
        assert!(output.contains("PersistentKeepalive = 25"));
        assert!(output.contains("# eastGate"));
        assert!(output.contains("PublicKey = <PUBLIC_KEY>"));
    }

    #[test]
    fn wg_quick_missing_pubkey_placeholder() {
        let conf = sample_config();
        let output = conf.to_wg_quick();
        let east_section = output.split("# eastGate").nth(1).unwrap();
        assert!(east_section.contains("<PUBLIC_KEY>"));
        assert!(!east_section.contains("Endpoint"));
        assert!(!east_section.contains("PersistentKeepalive"));
    }

    #[test]
    fn wg_quick_empty_allowed_ips_uses_mesh_ip() {
        let conf = sample_config();
        let output = conf.to_wg_quick();
        let east_section = output.split("# eastGate").nth(1).unwrap();
        assert!(east_section.contains("AllowedIPs = 10.13.37.5/32"));
    }

    #[test]
    fn display_delegates_to_wg_quick() {
        let conf = sample_config();
        assert_eq!(conf.to_string(), conf.to_wg_quick());
    }

    #[test]
    fn serde_roundtrip() {
        let conf = sample_config();
        let json = serde_json::to_string(&conf).unwrap();
        let parsed: WgConfig = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.gate_name, "sporeGate");
        assert_eq!(parsed.peers.len(), 2);
        assert_eq!(parsed.peers[0].public_key.as_deref(), Some("abc123=="));
    }
}
