// SPDX-License-Identifier: AGPL-3.0-or-later

//! Evidence manifest — BLAKE3 hash manifest for evidence depot integrity.
//!
//! Generates `evidence-manifest.toml` listing every file with its BLAKE3 hash,
//! size, and MIME type. The manifest is tracked in git for provenance even
//! though the evidence files themselves are not committed (too large / binary).

use crate::error::{Result, ShadowOutcome};

/// Generate an `evidence-manifest.toml` for the given evidence directory.
///
/// Walks all files, computes BLAKE3 hashes, and writes the manifest alongside
/// the evidence files. Returns a summary of what was manifested.
pub async fn generate_manifest(evidence_dir: &std::path::Path) -> Result<ShadowOutcome> {
    if !evidence_dir.exists() {
        return Ok(ShadowOutcome {
            ok: false,
            message: format!(
                "evidence manifest: directory does not exist — {}",
                evidence_dir.display()
            ),
            data: None,
        });
    }

    let files = super::collect_evidence_files(evidence_dir)?;

    if files.is_empty() {
        return Ok(ShadowOutcome::ok(
            "evidence manifest: no files to manifest (directory empty)".to_string(),
        ));
    }

    let mut entries = Vec::new();
    let mut total_bytes = 0u64;

    for file_path in &files {
        let rel_path = file_path
            .strip_prefix(evidence_dir)
            .unwrap_or(file_path.as_path());
        let rel_str = rel_path.to_string_lossy().replace('\\', "/");

        let hash = match crate::plasmid::compute_blake3_file_async(file_path).await {
            Ok(h) => h,
            Err(e) => {
                tracing::warn!(file = %rel_str, error = %e, "manifest: cannot hash");
                continue;
            }
        };

        let metadata = std::fs::metadata(file_path).ok();
        let size = metadata.as_ref().map(|m| m.len()).unwrap_or(0);
        total_bytes += size;

        let mime = mime_from_extension(file_path);

        entries.push(ManifestEntry {
            path: rel_str,
            blake3: hash,
            size,
            mime: mime.to_string(),
        });
    }

    // Build TOML content
    let mut toml = String::new();
    toml.push_str("# Evidence Manifest — auto-generated by cellMembrane\n");
    toml.push_str(&format!(
        "# Generated: {}\n",
        crate::utc_now_iso8601()
    ));
    toml.push_str(&format!(
        "# Files: {}, Total: {}\n\n",
        entries.len(),
        human_bytes(total_bytes)
    ));
    toml.push_str(&format!("file_count = {}\n", entries.len()));
    toml.push_str(&format!("total_bytes = {total_bytes}\n"));
    toml.push_str(&format!(
        "generated = \"{}\"\n\n",
        crate::utc_now_iso8601()
    ));

    for entry in &entries {
        toml.push_str(&format!("[[files]]\n"));
        toml.push_str(&format!("path = \"{}\"\n", entry.path));
        toml.push_str(&format!("blake3 = \"{}\"\n", entry.blake3));
        toml.push_str(&format!("size = {}\n", entry.size));
        toml.push_str(&format!("mime = \"{}\"\n\n", entry.mime));
    }

    let manifest_path = evidence_dir.join("evidence-manifest.toml");
    crate::atomic_write(&manifest_path, toml.as_bytes()).map_err(|e| {
        crate::error::ShadowError::Io(std::io::Error::other(format!(
            "cannot write manifest: {e}"
        )))
    })?;

    Ok(ShadowOutcome {
        ok: true,
        message: format!(
            "evidence manifest: {} files ({}) → {}",
            entries.len(),
            human_bytes(total_bytes),
            manifest_path.display()
        ),
        data: Some(serde_json::json!({
            "file_count": entries.len(),
            "total_bytes": total_bytes,
            "manifest_path": manifest_path.to_string_lossy(),
        })),
    })
}

struct ManifestEntry {
    path: String,
    blake3: String,
    size: u64,
    mime: String,
}

/// Infer MIME type from file extension.
fn mime_from_extension(path: &std::path::Path) -> &'static str {
    match path
        .extension()
        .and_then(|e| e.to_str())
        .map(|e| e.to_lowercase())
        .as_deref()
    {
        Some("pdf") => "application/pdf",
        Some("png") => "image/png",
        Some("jpg" | "jpeg") => "image/jpeg",
        Some("gif") => "image/gif",
        Some("webp") => "image/webp",
        Some("svg") => "image/svg+xml",
        Some("html" | "htm") => "text/html",
        Some("txt") => "text/plain",
        Some("md") => "text/markdown",
        Some("toml") => "application/toml",
        Some("json") => "application/json",
        Some("xml") => "application/xml",
        Some("csv") => "text/csv",
        Some("docx") => "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        Some("doc") => "application/msword",
        Some("msg") => "application/vnd.ms-outlook",
        _ => "application/octet-stream",
    }
}

/// Human-readable byte size.
fn human_bytes(bytes: u64) -> String {
    const KB: u64 = 1024;
    const MB: u64 = 1024 * KB;
    const GB: u64 = 1024 * MB;

    if bytes >= GB {
        format!("{:.1} GB", bytes as f64 / GB as f64)
    } else if bytes >= MB {
        format!("{:.1} MB", bytes as f64 / MB as f64)
    } else if bytes >= KB {
        format!("{:.1} KB", bytes as f64 / KB as f64)
    } else {
        format!("{bytes} B")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn mime_types_correct() {
        assert_eq!(
            mime_from_extension(std::path::Path::new("file.pdf")),
            "application/pdf"
        );
        assert_eq!(
            mime_from_extension(std::path::Path::new("image.PNG")),
            "image/png"
        );
        assert_eq!(
            mime_from_extension(std::path::Path::new("doc.docx")),
            "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
        );
        assert_eq!(
            mime_from_extension(std::path::Path::new("email.msg")),
            "application/vnd.ms-outlook"
        );
        assert_eq!(
            mime_from_extension(std::path::Path::new("unknown")),
            "application/octet-stream"
        );
    }

    #[test]
    fn human_bytes_formatting() {
        assert_eq!(human_bytes(0), "0 B");
        assert_eq!(human_bytes(512), "512 B");
        assert_eq!(human_bytes(1024), "1.0 KB");
        assert_eq!(human_bytes(1024 * 1024), "1.0 MB");
        assert_eq!(human_bytes(1024 * 1024 * 1024), "1.0 GB");
    }

    #[tokio::test]
    async fn generate_manifest_creates_file() {
        let dir = std::env::temp_dir().join("membrane-manifest-test");
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(dir.join("sub")).unwrap();
        std::fs::write(dir.join("test.pdf"), b"fake pdf content").unwrap();
        std::fs::write(dir.join("sub/image.png"), b"fake png").unwrap();

        let result = generate_manifest(&dir).await.unwrap();
        assert!(result.ok);
        assert!(result.message.contains("2 files"));

        let manifest = std::fs::read_to_string(dir.join("evidence-manifest.toml")).unwrap();
        assert!(manifest.contains("test.pdf"));
        assert!(manifest.contains("sub/image.png"));
        assert!(manifest.contains("application/pdf"));
        assert!(manifest.contains("image/png"));
        assert!(manifest.contains("blake3"));

        std::fs::remove_dir_all(&dir).ok();
    }

    #[tokio::test]
    async fn generate_manifest_empty_dir() {
        let dir = std::env::temp_dir().join("membrane-manifest-empty");
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();

        let result = generate_manifest(&dir).await.unwrap();
        assert!(result.ok);
        assert!(result.message.contains("empty"));

        std::fs::remove_dir_all(&dir).ok();
    }
}
