// SPDX-License-Identifier: AGPL-3.0-or-later

//! Gateway configuration helpers — pure functions for route generation,
//! songBird env/TOML bridging, and manifest-driven config derivation.
//!
//! Extracted from `gateway/mod.rs` to keep the dispatch module focused on
//! command orchestration while this module owns config transformation logic.

use crate::error::{Result, ShadowError};
use cellmembrane_types::gateway::{GatewayConfig, GatewayRoute};

/// Format a route for display.
#[must_use]
pub(super) fn format_route_line(route: &GatewayRoute) -> String {
    let path = if route.path_prefix.is_empty() {
        "/*"
    } else {
        &route.path_prefix
    };
    format!(
        "  {}{} → {} ({}s)",
        route.host, path, route.capability, route.timeout_secs
    )
}

/// Parse a port number from a bind address string (e.g. "0.0.0.0:443" → 443).
#[must_use]
pub(super) fn parse_port(bind: &str) -> Option<u16> {
    bind.rsplit(':').next()?.parse().ok()
}

/// Generate the `SONGBIRD_PROXY_ROUTES` env value from a gateway config.
///
/// songBird uses a comma-separated format: `host/path=capability,host/path=capability,...`
/// This bridges our typed `GatewayConfig` to songBird's runtime route table.
#[must_use]
pub(super) fn to_songbird_proxy_routes(config: &GatewayConfig) -> String {
    config
        .routes
        .iter()
        .map(|r| {
            let path = if r.path_prefix.is_empty() {
                "/*"
            } else {
                &r.path_prefix
            };
            format!("{}{path}={}", r.host, r.capability)
        })
        .collect::<Vec<_>>()
        .join(",")
}

/// Parse a `SONGBIRD_PROXY_ROUTES` env value back into route entries.
///
/// Inverse of [`to_songbird_proxy_routes`] — parses the runtime format back
/// into typed routes for validation or display.
#[cfg(test)]
#[must_use]
pub(super) fn parse_songbird_proxy_routes(env_val: &str) -> Vec<GatewayRoute> {
    env_val
        .split(',')
        .filter(|s| !s.is_empty())
        .filter_map(|entry| {
            let (host_path, capability) = entry.split_once('=')?;
            let (host, path_prefix) = host_path.find('/').map_or((host_path, "/*"), |pos| {
                (&host_path[..pos], &host_path[pos..])
            });
            Some(GatewayRoute {
                host: host.to_owned(),
                path_prefix: path_prefix.to_owned(),
                capability: capability.to_owned(),
                timeout_secs: cellmembrane_types::service::DEFAULT_GATEWAY_TIMEOUT_SECS,
            })
        })
        .collect()
}

/// Generate songBird's `ReverseProxyConfig` TOML format from gateway routes.
///
/// songBird reads a TOML configuration file with `[[routes]]` entries. This
/// function bridges our typed `GatewayConfig` to that file format, enabling
/// cellMembrane to produce the config file songBird loads at startup.
///
/// Format:
/// ```toml
/// [[routes]]
/// host = "lab.primals.eco"
/// path_prefix = "/hub"
/// capability = "jupyter"
/// timeout_secs = 30
/// ```
#[cfg(test)]
#[must_use]
pub(super) fn to_songbird_routes_toml(config: &GatewayConfig) -> String {
    use std::fmt::Write;

    let mut out = String::new();
    let _ = writeln!(
        out,
        "# songBird ReverseProxyConfig — generated by cellMembrane"
    );
    let _ = writeln!(
        out,
        "# Gate: {} | Routes: {}",
        config.gate_name,
        config.routes.len()
    );
    let _ = writeln!(out);

    for route in &config.routes {
        let _ = writeln!(out, "[[routes]]");
        let _ = writeln!(out, "host = \"{}\"", route.host);
        let path = if route.path_prefix.is_empty() {
            "/"
        } else {
            &route.path_prefix
        };
        let _ = writeln!(out, "path_prefix = \"{path}\"");
        let _ = writeln!(out, "capability = \"{}\"", route.capability);
        let _ = writeln!(out, "timeout_secs = {}", route.timeout_secs);
        let _ = writeln!(out);
    }

    out
}

/// Generate default gateway routes based on a gate's roles.
///
/// Pure function: maps role strings to default route configurations.
/// Gates with `http` or `gateway` roles get the standard `JupyterHub` routes.
#[must_use]
pub(super) fn default_routes_for_roles(roles: &[cellmembrane_types::GateRole]) -> Vec<GatewayRoute> {
    use cellmembrane_types::GateRole;
    let has_http_role = roles
        .iter()
        .any(|r| matches!(r, GateRole::Http | GateRole::Gateway));

    if !has_http_role {
        return Vec::new();
    }

    let timeout = cellmembrane_types::service::DEFAULT_GATEWAY_TIMEOUT_SECS;
    let host = "lab.primals.eco";

    vec![
        GatewayRoute {
            host: host.into(),
            path_prefix: "/hub".into(),
            capability: "jupyter".into(),
            timeout_secs: timeout,
        },
        GatewayRoute {
            host: host.into(),
            path_prefix: "/user".into(),
            capability: "jupyter".into(),
            timeout_secs: timeout,
        },
        GatewayRoute {
            host: host.into(),
            path_prefix: "/api".into(),
            capability: "jupyter".into(),
            timeout_secs: timeout,
        },
        GatewayRoute {
            host: host.into(),
            path_prefix: "/services".into(),
            capability: "jupyter".into(),
            timeout_secs: timeout,
        },
    ]
}

/// Generate a gateway config from the ecosystem manifest for a specific gate.
pub(super) fn generate_from_manifest(gate_name: &str) -> Result<GatewayConfig> {
    let root = crate::temporal::resolve_workspace_root()?;
    let manifest = crate::manifest::load_from_workspace(&root)?;
    let profile = manifest.gates.get(gate_name).ok_or_else(|| {
        ShadowError::Config(format!("gate '{gate_name}' not in ecosystem manifest"))
    })?;

    let routes = default_routes_for_roles(&profile.roles);

    Ok(GatewayConfig {
        gate_name: gate_name.into(),
        enabled: true,
        max_connections: cellmembrane_types::service::DEFAULT_GATEWAY_MAX_CONNECTIONS,
        default_timeout_secs: cellmembrane_types::service::DEFAULT_GATEWAY_TIMEOUT_SECS,
        routes,
    })
}

/// Load gateway config from a TOML file path (first arg) or default location.
pub(crate) fn load_gateway_config(args: &[&str]) -> Result<GatewayConfig> {
    let path = args.first().map_or_else(
        || {
            let config_dir = cellmembrane_types::service::env_or(
                cellmembrane_types::service::ENV_CONFIG_DIR,
                cellmembrane_types::service::DEFAULT_CONFIG_DIR,
            );
            format!("{config_dir}/gateway.toml")
        },
        |p| (*p).to_string(),
    );

    let content = std::fs::read_to_string(&path)
        .map_err(|e| ShadowError::Config(format!("cannot read gateway config at {path}: {e}")))?;

    toml::from_str(&content)
        .map_err(|e| ShadowError::Config(format!("invalid gateway config: {e}")))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_port_from_bind() {
        assert_eq!(parse_port("0.0.0.0:443"), Some(443));
        assert_eq!(parse_port("127.0.0.1:8443"), Some(8443));
        assert_eq!(parse_port("443"), Some(443));
    }

    #[test]
    fn parse_port_invalid() {
        assert_eq!(parse_port(""), None);
        assert_eq!(parse_port("no-port"), None);
    }

    #[test]
    fn format_route_line_with_path() {
        let route = GatewayRoute {
            host: "lab.primals.eco".into(),
            path_prefix: "/hub".into(),
            capability: "jupyter".into(),
            timeout_secs: 30,
        };
        let line = format_route_line(&route);
        assert!(line.contains("lab.primals.eco/hub"));
        assert!(line.contains("jupyter"));
        assert!(line.contains("30s"));
    }

    #[test]
    fn format_route_line_empty_path() {
        let route = GatewayRoute {
            host: "lab.primals.eco".into(),
            path_prefix: String::new(),
            capability: "compute".into(),
            timeout_secs: 60,
        };
        let line = format_route_line(&route);
        assert!(line.contains("/*"));
        assert!(line.contains("compute"));
    }

    #[test]
    fn to_songbird_proxy_routes_generates_env() {
        let config = GatewayConfig {
            gate_name: "sporeGate".into(),
            enabled: true,
            max_connections: 100,
            default_timeout_secs: 30,
            routes: vec![
                GatewayRoute {
                    host: "lab.primals.eco".into(),
                    path_prefix: "/hub".into(),
                    capability: "jupyter".into(),
                    timeout_secs: 30,
                },
                GatewayRoute {
                    host: "lab.primals.eco".into(),
                    path_prefix: "/api".into(),
                    capability: "jupyter".into(),
                    timeout_secs: 30,
                },
            ],
        };
        let env = to_songbird_proxy_routes(&config);
        assert_eq!(
            env,
            "lab.primals.eco/hub=jupyter,lab.primals.eco/api=jupyter"
        );
    }

    #[test]
    fn to_songbird_proxy_routes_empty_path() {
        let config = GatewayConfig {
            gate_name: "test".into(),
            enabled: true,
            max_connections: 100,
            default_timeout_secs: 30,
            routes: vec![GatewayRoute {
                host: "lab.primals.eco".into(),
                path_prefix: String::new(),
                capability: "compute".into(),
                timeout_secs: 30,
            }],
        };
        let env = to_songbird_proxy_routes(&config);
        assert_eq!(env, "lab.primals.eco/*=compute");
    }

    #[test]
    fn parse_songbird_proxy_routes_roundtrip() {
        let env_val = "lab.primals.eco/hub=jupyter,lab.primals.eco/api=jupyter";
        let routes = parse_songbird_proxy_routes(env_val);
        assert_eq!(routes.len(), 2);
        assert_eq!(routes[0].host, "lab.primals.eco");
        assert_eq!(routes[0].path_prefix, "/hub");
        assert_eq!(routes[0].capability, "jupyter");
        assert_eq!(routes[1].path_prefix, "/api");
    }

    #[test]
    fn parse_songbird_proxy_routes_empty() {
        assert!(parse_songbird_proxy_routes("").is_empty());
    }

    #[test]
    fn parse_songbird_proxy_routes_no_path() {
        let routes = parse_songbird_proxy_routes("example.com=service");
        assert_eq!(routes.len(), 1);
        assert_eq!(routes[0].host, "example.com");
        assert_eq!(routes[0].path_prefix, "/*");
        assert_eq!(routes[0].capability, "service");
    }

    #[test]
    fn parse_songbird_proxy_routes_skips_invalid() {
        let routes = parse_songbird_proxy_routes("valid.host/path=cap,invalid_no_equals");
        assert_eq!(routes.len(), 1);
        assert_eq!(routes[0].host, "valid.host");
    }

    #[test]
    fn default_routes_for_http_role() {
        use cellmembrane_types::GateRole;
        let roles = vec![GateRole::Http, GateRole::Ci];
        let routes = default_routes_for_roles(&roles);
        assert_eq!(routes.len(), 4);
        assert!(routes.iter().all(|r| r.host == "lab.primals.eco"));
        assert!(routes.iter().any(|r| r.path_prefix == "/hub"));
        assert!(routes.iter().any(|r| r.path_prefix == "/user"));
        assert!(routes.iter().any(|r| r.path_prefix == "/api"));
        assert!(routes.iter().any(|r| r.path_prefix == "/services"));
    }

    #[test]
    fn default_routes_for_gateway_role() {
        use cellmembrane_types::GateRole;
        let roles = vec![GateRole::Gateway];
        let routes = default_routes_for_roles(&roles);
        assert_eq!(routes.len(), 4);
    }

    #[test]
    fn default_routes_for_non_http_role() {
        use cellmembrane_types::GateRole;
        let roles = vec![GateRole::Ci, GateRole::Compute];
        let routes = default_routes_for_roles(&roles);
        assert!(routes.is_empty());
    }

    #[test]
    fn default_routes_empty_roles() {
        let routes = default_routes_for_roles(&[]);
        assert!(routes.is_empty());
    }

    #[test]
    fn to_songbird_routes_toml_generates_valid_toml() {
        let config = GatewayConfig {
            gate_name: "sporeGate".into(),
            enabled: true,
            max_connections: 100,
            default_timeout_secs: 30,
            routes: vec![
                GatewayRoute {
                    host: "lab.primals.eco".into(),
                    path_prefix: "/hub".into(),
                    capability: "jupyter".into(),
                    timeout_secs: 30,
                },
                GatewayRoute {
                    host: "lab.primals.eco".into(),
                    path_prefix: "/api".into(),
                    capability: "jupyter".into(),
                    timeout_secs: 30,
                },
            ],
        };
        let toml_str = to_songbird_routes_toml(&config);
        assert!(toml_str.contains("[[routes]]"));
        assert!(toml_str.contains("host = \"lab.primals.eco\""));
        assert!(toml_str.contains("path_prefix = \"/hub\""));
        assert!(toml_str.contains("capability = \"jupyter\""));
        assert!(toml_str.contains("timeout_secs = 30"));
        assert!(toml_str.contains("sporeGate"));
        let count = toml_str.matches("[[routes]]").count();
        assert_eq!(count, 2, "should have 2 route sections");
    }

    #[test]
    fn to_songbird_routes_toml_empty_path_defaults_to_slash() {
        let config = GatewayConfig {
            gate_name: "test".into(),
            enabled: true,
            max_connections: 100,
            default_timeout_secs: 30,
            routes: vec![GatewayRoute {
                host: "example.com".into(),
                path_prefix: String::new(),
                capability: "compute".into(),
                timeout_secs: 60,
            }],
        };
        let toml_str = to_songbird_routes_toml(&config);
        assert!(toml_str.contains("path_prefix = \"/\""));
    }
}
