// SPDX-License-Identifier: AGPL-3.0-or-later

//! Freshness tracking — per-gate HEAD SHAs and binary provenance drift detection.
//!
//! Architecture (Wave 131+):
//! - `wave.toml` — human-authored wave metadata (overwatch sole writer)
//! - `heads/<gate>.toml` — per-gate HEAD SHAs (each gate writes only its own file)
//! - `freshness.toml` — DEPRECATED unified view (generated by `unify_freshness`)
//!
//! - `publish_gate_heads()` — writes `heads/<gate>.toml` with this gate's HEAD SHAs.
//! - `unify_freshness()` — reads `wave.toml` + `heads/*.toml` → writes `freshness.toml` (golgi only).
//! - `check_installed_freshness()` — compares installed binary provenance against source.

use crate::error::{Result, ShadowError};
pub use crate::sovereignty_ledger::{SovereigntyCheck, rootpulse_commit, sovereignty_verify};
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use tracing::warn;

const FRESHNESS_HEADER: &str = "\
# SPDX-License-Identifier: CC-BY-SA-4.0
#
# freshness.toml — DEPRECATED: unified view generated from wave.toml + heads/*.toml
#
# DO NOT EDIT THIS FILE DIRECTLY.
# Wave metadata: wave.toml (overwatch sole writer)
# Per-gate heads: heads/<gate>.toml (each gate sole writer of its own file)
#
# Regenerated by: membrane temporal.cascade --unify-freshness (golgi timer)
";

const GATE_HEADS_HEADER: &str = "\
# Auto-published by membrane temporal.cascade --publish-freshness
# This file is owned exclusively by this gate. No other gate writes here.
";

/// Serializable representation of `freshness.toml` (backward compat).
#[derive(Debug, Serialize, Deserialize)]
struct FreshnessFile {
    wave: WaveSection,
    #[serde(default)]
    heads: BTreeMap<String, String>,
}

#[derive(Debug, Serialize, Deserialize)]
struct WaveSection {
    id: u32,
    #[serde(default)]
    date: String,
    #[serde(default)]
    ssot: String,
    #[serde(default)]
    notes: String,
    #[serde(default)]
    publisher: String,
    #[serde(default)]
    posture: String,
}

/// Per-gate heads file representation.
#[derive(Debug, Serialize, Deserialize)]
struct GateHeadsFile {
    meta: GateHeadsMeta,
    #[serde(default)]
    heads: BTreeMap<String, String>,
}

#[derive(Debug, Serialize, Deserialize)]
struct GateHeadsMeta {
    gate: String,
    updated: String,
}

/// wave.toml representation.
#[derive(Debug, Serialize, Deserialize)]
struct WaveFile {
    wave: WaveSection,
    #[serde(default)]
    gates: Option<GatesSection>,
}

#[derive(Debug, Serialize, Deserialize)]
struct GatesSection {
    #[serde(default)]
    online: Vec<String>,
    #[serde(default)]
    offline: Vec<String>,
}

// ── Per-Gate Head Publishing ─────────────────────────────────────────

/// Publish this gate's HEAD SHAs to `heads/<gate>.toml`.
///
/// Each gate writes ONLY its own file — zero conflict with other gates.
/// Replaces the old `publish_freshness_toml` which wrote a single shared file.
pub async fn publish_gate_heads(
    root: &Path,
    repos: &[(&str, &crate::manifest::RepoEntry)],
) -> Result<()> {
    let gate = resolve_gate_name(root).await;
    let heads_dir = root
        .join(cellmembrane_types::service::INFRA_WATERING_HOLE)
        .join("heads");

    tokio::fs::create_dir_all(&heads_dir)
        .await
        .map_err(ShadowError::Io)?;

    let mut heads = BTreeMap::new();
    for (name, entry) in repos {
        let repo_dir = root.join(&entry.local_path);
        if repo_dir.join(".git").exists() {
            if let Ok(sha) = git_rev_parse_head(&repo_dir).await {
                if is_valid_sha(&sha) {
                    heads.insert((*name).to_string(), sha);
                } else {
                    warn!(repo = *name, sha = %sha, "Rejected truncated/corrupt SHA — skipping head");
                }
            }
        }
    }

    let file = GateHeadsFile {
        meta: GateHeadsMeta {
            gate: gate.clone(),
            updated: chrono_now_utc(),
        },
        heads,
    };

    let body = toml::to_string_pretty(&file).map_err(ShadowError::Serialize)?;
    let content = format!("{GATE_HEADS_HEADER}# Gate: {gate} | Updated: {}\n\n{body}", file.meta.updated);
    let heads_path = heads_dir.join(format!("{gate}.toml"));
    crate::atomic_write_async(&heads_path, content.as_bytes())
        .await
        .map_err(ShadowError::Io)?;

    Ok(())
}

/// Auto-commit and push this gate's heads file after cascade.
///
/// Pulls from remote first (to avoid push rejection), then commits
/// only `heads/<gate>.toml`. Since each gate owns its own file,
/// conflicts are structurally impossible.
pub async fn auto_commit_gate_heads(
    root: &Path,
    repos: &[(&str, &crate::manifest::RepoEntry)],
) -> Result<bool> {
    let wh_dir = root.join(cellmembrane_types::service::INFRA_WATERING_HOLE);
    if !wh_dir.join(".git").exists() {
        return Err(ShadowError::Config(
            "wateringHole not a git repo — cannot auto-commit heads".into(),
        ));
    }

    let gate = resolve_gate_name(root).await;

    pull_ff_only(&wh_dir).await;

    publish_gate_heads(root, repos).await?;

    let heads_file = format!("heads/{gate}.toml");
    if !crate::git_ops::git_success(&wh_dir, &["add", &heads_file]).await {
        return Ok(false);
    }

    if crate::git_ops::git_success(&wh_dir, &["diff", "--cached", "--quiet"]).await {
        return Ok(false);
    }

    let msg = format!("heads/{gate}: auto-publish by {gate}");
    crate::git_ops::run_git(&wh_dir, &["commit", "-m", &msg]).await?;

    let push_result = crate::git_ops::push_all_remotes(&wh_dir).await;
    if !push_result.failed.is_empty() {
        warn!(
            failed_remotes = %push_result.failed.join(", "),
            "gate heads push failed — will retry next cycle"
        );
    }

    Ok(true)
}

// ── Unified Freshness (golgi only, backward compat) ─────────────────

/// Merge `wave.toml` + all `heads/*.toml` into a single `freshness.toml`.
///
/// Run ONLY on golgi (the quorum timer gate) for backward compatibility.
/// Once all consumers migrate to reading `wave.toml` + `heads/*.toml` directly,
/// this function and `freshness.toml` can be removed.
pub async fn unify_freshness(root: &Path) -> Result<()> {
    let wh_dir = root.join(cellmembrane_types::service::INFRA_WATERING_HOLE);
    let wave_path = wh_dir.join("wave.toml");
    let heads_dir = wh_dir.join("heads");
    let freshness_path = wh_dir.join("freshness.toml");

    let wave: WaveFile = tokio::fs::read_to_string(&wave_path)
        .await
        .ok()
        .and_then(|c| toml::from_str(&c).ok())
        .unwrap_or_else(|| WaveFile {
            wave: WaveSection {
                id: 0,
                date: chrono_today(),
                ssot: String::new(),
                notes: "wave.toml not found".into(),
                publisher: String::new(),
                posture: String::new(),
            },
            gates: None,
        });

    let mut merged_heads = BTreeMap::new();

    if let Ok(mut entries) = tokio::fs::read_dir(&heads_dir).await {
        while let Ok(Some(entry)) = entries.next_entry().await {
            let path = entry.path();
            if path.extension().is_some_and(|e| e == "toml") {
                if let Ok(content) = tokio::fs::read_to_string(&path).await {
                    if let Ok(gate_file) = toml::from_str::<GateHeadsFile>(&content) {
                        for (repo, sha) in gate_file.heads {
                            merged_heads.insert(repo, sha);
                        }
                    }
                }
            }
        }
    }

    let unified = FreshnessFile {
        wave: wave.wave,
        heads: merged_heads,
    };

    let body = toml::to_string_pretty(&unified).map_err(ShadowError::Serialize)?;
    let content = format!("{FRESHNESS_HEADER}\n{body}");
    crate::atomic_write_async(&freshness_path, content.as_bytes())
        .await
        .map_err(ShadowError::Io)?;

    Ok(())
}

// ── Legacy Compatibility ─────────────────────────────────────────────

/// DEPRECATED: Publish `freshness.toml` directly.
///
/// Retained for backward compat during migration. New code should use
/// `publish_gate_heads()` + `unify_freshness()`.
pub async fn publish_freshness_toml(
    root: &Path,
    manifest: &crate::manifest::EcosystemManifest,
    repos: &[(&str, &crate::manifest::RepoEntry)],
) -> Result<()> {
    let freshness_path = root
        .join(cellmembrane_types::service::INFRA_WATERING_HOLE)
        .join("freshness.toml");

    let mut heads = tokio::fs::read_to_string(&freshness_path)
        .await
        .ok()
        .and_then(|c| toml::from_str::<FreshnessFile>(&c).ok())
        .map_or_else(BTreeMap::new, |f| f.heads);

    for (name, entry) in repos {
        let repo_dir = root.join(&entry.local_path);
        if repo_dir.join(".git").exists() {
            if let Ok(sha) = git_rev_parse_head(&repo_dir).await {
                heads.insert((*name).to_string(), sha);
            }
        }
    }

    let file = FreshnessFile {
        wave: WaveSection {
            id: manifest.meta.wave,
            date: chrono_today(),
            ssot: "specs/WATERFALL_TEMPORAL_SYNC.md".into(),
            notes: "Auto-published by membrane temporal.cascade --publish-freshness".into(),
            publisher: "membrane".into(),
            posture: String::new(),
        },
        heads,
    };

    let body = toml::to_string_pretty(&file).map_err(ShadowError::Serialize)?;
    let content = format!("{FRESHNESS_HEADER}\n{body}");
    crate::atomic_write_async(&freshness_path, content.as_bytes())
        .await
        .map_err(ShadowError::Io)?;

    // Also write per-gate heads (dual-write during migration).
    publish_gate_heads(root, repos).await?;

    Ok(())
}

/// DEPRECATED: Auto-commit freshness.toml.
///
/// Now dual-writes: commits both `freshness.toml` (legacy) and `heads/<gate>.toml` (new).
/// Once all consumers migrate, this becomes just `auto_commit_gate_heads`.
pub async fn auto_commit_freshness(
    root: &Path,
    manifest: &crate::manifest::EcosystemManifest,
    repos: &[(&str, &crate::manifest::RepoEntry)],
) -> Result<()> {
    let wh_dir = root.join(cellmembrane_types::service::INFRA_WATERING_HOLE);
    if !wh_dir.join(".git").exists() {
        return Err(ShadowError::Config(
            "wateringHole not a git repo — cannot auto-commit freshness".into(),
        ));
    }

    let gate = resolve_gate_name(root).await;

    pull_ff_only(&wh_dir).await;

    publish_freshness_toml(root, manifest, repos).await?;

    let heads_file = format!("heads/{gate}.toml");
    if !crate::git_ops::git_success(&wh_dir, &["add", "freshness.toml", &heads_file]).await {
        return Ok(());
    }

    if crate::git_ops::git_success(&wh_dir, &["diff", "--cached", "--quiet"]).await {
        return Ok(());
    }

    let msg = format!("freshness: auto-publish by {gate}");
    crate::git_ops::run_git(&wh_dir, &["commit", "-m", &msg]).await?;

    let push_result = crate::git_ops::push_all_remotes(&wh_dir).await;
    if !push_result.failed.is_empty() {
        warn!(
            failed_remotes = %push_result.failed.join(", "),
            "freshness push failed — will retry next cycle"
        );
    }

    Ok(())
}

/// Convenience wrapper: loads manifest from workspace root and calls
/// `auto_commit_freshness`. Returns `Ok(true)` when a commit was made,
/// `Ok(false)` when nothing changed.
pub async fn auto_commit_unified_freshness(root: &Path) -> Result<bool> {
    let manifest = crate::manifest::load_from_workspace(root)?;
    let repo_vec: Vec<(String, crate::manifest::RepoEntry)> = manifest
        .repos
        .iter()
        .map(|(k, v)| (k.clone(), v.clone()))
        .collect();
    let repo_refs: Vec<(&str, &crate::manifest::RepoEntry)> =
        repo_vec.iter().map(|(k, v)| (k.as_str(), v)).collect();

    let wh_dir = root.join(cellmembrane_types::service::INFRA_WATERING_HOLE);
    let had_changes_before = !crate::git_ops::git_success(
        &wh_dir,
        &["diff", "--quiet", "freshness.toml"],
    )
    .await;

    auto_commit_freshness(root, &manifest, &repo_refs).await?;

    let had_changes_after = !crate::git_ops::git_success(
        &wh_dir,
        &["diff", "--quiet", "freshness.toml"],
    )
    .await;

    Ok(!had_changes_before && !had_changes_after || had_changes_before)
}

// ── Helpers ──────────────────────────────────────────────────────────

/// Pull with fast-forward only — no rebase, no conflict resolution.
/// If FF fails, just skip (push will fail and retry next cycle).
async fn pull_ff_only(wh_dir: &Path) {
    for remote in cellmembrane_types::service::DEFAULT_PUSH_REMOTES {
        let result = crate::git_ops::git_output(wh_dir, &["pull", "--ff-only", remote, "main"]).await;
        if let Err(e) = result {
            let msg = e.to_string();
            if !msg.contains("Already up to date") {
                tracing::debug!(%msg, %remote, "FF pull failed — will retry on next push");
            }
        }
    }
}

/// Resolve the local gate name from env or `.gate` file.
async fn resolve_gate_name(root: &Path) -> String {
    match std::env::var(cellmembrane_types::service::ENV_GATE_NAME) {
        Ok(g) => g,
        Err(_) => tokio::fs::read_to_string(root.join(".gate"))
            .await
            .map_or_else(
                |_| crate::gate::resolve_local_gate_identity(),
                |s| s.trim().to_string(),
            ),
    }
}

/// Parse the wave ID from a freshness.toml file. Returns 0 if unreadable.
#[cfg(test)]
fn read_freshness_wave_id(path: &Path) -> u32 {
    let Ok(content) = std::fs::read_to_string(path) else {
        return 0;
    };
    toml::from_str::<FreshnessFile>(&content).map_or(0, |f| f.wave.id)
}

/// Async variant — reads the file without blocking the runtime.
#[allow(dead_code)]
async fn read_freshness_wave_id_async(path: &Path) -> u32 {
    let Ok(content) = tokio::fs::read_to_string(path).await else {
        return 0;
    };
    toml::from_str::<FreshnessFile>(&content).map_or(0, |f| f.wave.id)
}

/// Check installed binary freshness against source HEAD SHAs.
///
/// Reads provenance sidecars from `~/.local/share/ecoPrimals/provenance/`
/// (written by `plasmidbin install`) and compares `build_commit` against
/// the current HEAD of each primal's local source repo.
///
/// Returns a formatted report string showing drift status per binary.
pub(crate) fn check_installed_freshness() -> Result<String> {
    use std::fmt::Write;

    let provenance_dir = dirs_provenance();
    if !provenance_dir.exists() {
        return Ok("No provenance sidecars found (plasmidbin not yet installed binaries).".into());
    }

    let root = crate::temporal::resolve_workspace_root()?;
    let mut report = String::from("=== Binary Freshness Check ===\n");
    let mut fresh = 0u32;
    let mut stale = 0u32;
    let mut unknown = 0u32;

    let Ok(entries) = std::fs::read_dir(&provenance_dir) else {
        return Ok("Cannot read provenance directory.".into());
    };

    for entry in entries.flatten() {
        let path = entry.path();
        if path.extension().is_none_or(|e| e != "toml") {
            continue;
        }

        let Ok(contents) = std::fs::read_to_string(&path) else {
            continue;
        };

        let Ok(prov) = toml::from_str::<ProvenanceSidecar>(&contents) else {
            continue;
        };

        let primal_name = path
            .file_stem()
            .unwrap_or_default()
            .to_string_lossy()
            .to_string();

        let source_head = resolve_source_head(&root, &prov.source_path);

        let age = prov.installed_at.as_deref().unwrap_or("?");
        let hash_short = prov
            .binary_blake3
            .as_deref()
            .map_or_else(|| "-".to_string(), |h| h[..8.min(h.len())].to_string());

        let status = match &source_head {
            Some(head) if head == &prov.build_commit => {
                fresh += 1;
                format!("FRESH (b3={hash_short}) [{age}]")
            }
            Some(head) => {
                stale += 1;
                format!(
                    "STALE (installed={}, HEAD={}, b3={hash_short}) [{age}]",
                    &prov.build_commit[..8.min(prov.build_commit.len())],
                    &head[..8.min(head.len())]
                )
            }
            None => {
                unknown += 1;
                format!("UNKNOWN (source not found, b3={hash_short}) [{age}]")
            }
        };

        writeln!(report, "  {primal_name:<20} {status}").ok();
    }

    writeln!(report, "\nfresh={fresh} stale={stale} unknown={unknown}").ok();
    Ok(report)
}

// ── Helpers ──────────────────────────────────────────────────────────

/// Get today's date as YYYY-MM-DD.
fn chrono_today() -> String {
    chrono::Utc::now().format("%Y-%m-%d").to_string()
}

/// Get current UTC timestamp as ISO 8601.
fn chrono_now_utc() -> String {
    chrono::Utc::now().format("%Y-%m-%dT%H:%M:%SZ").to_string()
}

/// Provenance sidecar written by `plasmidbin install`.
#[derive(Debug, serde::Deserialize)]
struct ProvenanceSidecar {
    build_commit: String,
    source_path: String,
    installed_at: Option<String>,
    binary_blake3: Option<String>,
}

/// Standard provenance directory (XDG data dir).
fn dirs_provenance() -> PathBuf {
    crate::resolve_xdg_data_home()
        .join("ecoPrimals")
        .join("provenance")
}

/// Get full HEAD SHA of a source repo given its path (sync).
fn resolve_source_head(workspace_root: &Path, source_path: &str) -> Option<String> {
    let repo_dir = if PathBuf::from(source_path).is_absolute() {
        PathBuf::from(source_path)
    } else {
        workspace_root.join(source_path)
    };
    crate::git_ops::resolve_head_full(&repo_dir)
}

/// Async git rev-parse HEAD.
async fn git_rev_parse_head(repo_dir: &Path) -> Result<String> {
    crate::git_ops::git_output(repo_dir, &["rev-parse", "HEAD"]).await
}

/// Reject truncated or corrupt SHAs.
///
/// Valid: 40 hex chars without long zero tails (which indicate failed rev-parse
/// on shallow clones — e.g. `05e22043…000000`).
fn is_valid_sha(sha: &str) -> bool {
    let trimmed = sha.trim();
    trimmed.len() == 40
        && trimmed.chars().all(|c| c.is_ascii_hexdigit())
        && !trimmed.ends_with("0000000000000000000000000000")
}

/// Read the current wave ID from `freshness.toml` in the workspace.
///
/// Returns `0` if the file is missing, unparseable, or has no wave ID.
/// This is the canonical source — do not duplicate.
#[must_use]
pub(crate) fn current_wave(workspace_root: &Path) -> u32 {
    let path = workspace_root
        .join(cellmembrane_types::service::INFRA_WATERING_HOLE)
        .join("freshness.toml");
    let Ok(content) = std::fs::read_to_string(&path) else {
        return 0;
    };
    toml::from_str::<FreshnessFile>(&content).map_or(0, |f| f.wave.id)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn chrono_today_format() {
        let today = chrono_today();
        assert_eq!(today.len(), 10);
        assert_eq!(&today[4..5], "-");
        assert_eq!(&today[7..8], "-");
        let year: u32 = today[..4].parse().unwrap();
        assert!(year >= 2024);
    }

    #[test]
    fn dirs_provenance_uses_xdg() {
        let dir = dirs_provenance();
        assert!(dir.to_string_lossy().contains("ecoPrimals/provenance"));
    }

    #[test]
    fn resolve_source_head_returns_none_for_missing() {
        let result = resolve_source_head(Path::new("/tmp"), "nonexistent-repo-xyz");
        assert!(result.is_none());
    }

    #[test]
    fn resolve_source_head_handles_absolute_path() {
        let result = resolve_source_head(Path::new("/tmp"), "/tmp/no-such-dir");
        assert!(result.is_none());
    }

    #[test]
    fn provenance_sidecar_deserializes() {
        let toml_str = r#"
build_commit = "abc12345"
source_path = "primals/bearDog"
installed_at = "2026-06-07T12:00:00Z"
binary_blake3 = "deadbeef0123456789"
"#;
        let prov: ProvenanceSidecar = toml::from_str(toml_str).unwrap();
        assert_eq!(prov.build_commit, "abc12345");
        assert_eq!(prov.source_path, "primals/bearDog");
        assert_eq!(prov.installed_at.as_deref(), Some("2026-06-07T12:00:00Z"));
        assert_eq!(prov.binary_blake3.as_deref(), Some("deadbeef0123456789"));
    }

    #[test]
    fn provenance_sidecar_optional_fields() {
        let toml_str = r#"
build_commit = "abc12345"
source_path = "primals/bearDog"
"#;
        let prov: ProvenanceSidecar = toml::from_str(toml_str).unwrap();
        assert!(prov.installed_at.is_none());
        assert!(prov.binary_blake3.is_none());
    }

    #[test]
    fn read_freshness_wave_id_parses_correctly() {
        use std::io::Write as IoWrite;
        let dir = std::env::temp_dir().join("freshness-test");
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("freshness.toml");
        let mut f = std::fs::File::create(&path).unwrap();
        writeln!(f, "[wave]").unwrap();
        writeln!(f, "id = 111").unwrap();
        writeln!(f, "date = \"2026-06-12\"").unwrap();
        drop(f);
        assert_eq!(read_freshness_wave_id(&path), 111);
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn read_freshness_wave_id_returns_zero_for_missing() {
        assert_eq!(
            read_freshness_wave_id(Path::new("/tmp/nonexistent-freshness-xyz.toml")),
            0
        );
    }

    #[test]
    fn valid_sha_accepts_normal_hex() {
        assert!(is_valid_sha("f3006ccde4d0a72b8ef5c3e1a9d456f78901ab23"));
    }

    #[test]
    fn valid_sha_rejects_truncated_zeros() {
        assert!(!is_valid_sha("05e2204300000000000000000000000000000000"));
        assert!(!is_valid_sha("d95c012000000000000000000000000000000000"));
    }

    #[test]
    fn valid_sha_rejects_wrong_length() {
        assert!(!is_valid_sha("abc123"));
        assert!(!is_valid_sha(""));
    }

    #[test]
    fn valid_sha_rejects_non_hex() {
        assert!(!is_valid_sha("zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"));
    }
}
